import = [
    "~/.config/alacritty/dracula.toml"
]

[bell]
duration = 0

[font]
size = 20.0

[font.bold]
family = "Inconsolata"

[font.italic]
family = "Inconsolata"

[font.normal]
family = "Inconsolata"

[[hints.enabled]]
command = "xdg-open"
post_processing = true
# KISS: RFC-3986 URI allows square brackets for IPv6address and IPvFuture
# But rejecting [] fixes URI regex by skipping the label part in AsciiDoc link.
regex = "(mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`\\[\\]]+"

[hints.enabled.mouse]
enabled = true
mods = "None"

[[keyboard.bindings]]
action = "ClearHistory"
key = "K"
mods = "Control"

[window]
decorations = "full"

[window.padding]
x = 2
y = 2
