#!/bin/sh

# Restore XKB on exit
restore_xkb()
{
    xmodmap $HOME/.config/xkb/xmodmap.capslockmustdie
}
trap restore_xkb EXIT

# Remap WASD_QE to IJKL_UO for Iratus game
xmodmap $HOME/.config/xkb/xmodmap.ijkl_uo

$HOME/Games/Iratus/start.sh
